services:
  my_rust_app:
    image: srinivasanbigdata/azure_vault_file_upload
    volumes:
      - ./.env:/usr/src/app/.env
      - ./data:/usr/src/app/data
    command: ["sh", "azure_upload.sh", "--secret-name", "argument1", "--file-path", "data/a.key"]
